export default {
  SIGNIN: 'SIGNIN',
  SIGNOUT: 'SIGNOUT',
  SET_USER: 'SET_USER',
  SET_AVATAR: 'SET_AVATAR',
  OPEN_PROFILE: 'OPEN_PROFILE',
  CLOSE_PROFILE: 'CLOSE_PROFILE',
  SET_TOKEN: 'SET_TOKEN',
  OPEN_CHAT: 'OPEN_CHAT',
  OPEN_USER: 'OPEN_USER',
  ADD_CHAT: 'ADD_CHAT',
  DELETE_CHAT: 'DELETE_CHAT',
  SEARCH: 'SEARCH',
  CLEAR_SEARCH: 'CLEAR_SEARCH',
  ADD_MESSAGE: 'ADD_MESSAGE',
  CLOSE_CURRENT: 'CLOSE_CURRENT',
  ADD_CURRENT_MESSAGE: 'ADD_CURRENT_MESSAGE'
};